channels:
- conda-forge
dependencies:
- pip=24.0
- python=3.11.9
- pip:
  - annotated-types==0.7.0
  - anyio==4.4.0
  - anywidget==0.9.12
  - appnope==0.1.4
  - argon2-cffi==23.1.0
  - argon2-cffi-bindings==21.2.0
  - arrow==1.3.0
  - asciitree==0.3.3
  - astropy==6.1.0
  - astropy-healpix==1.0.3
  - astropy-iers-data==0.2024.6.10.0.30.47
  - asttokens==2.4.1
  - async-lru==2.0.4
  - attrs==23.2.0
  - authlib==1.3.1
  - babel==2.15.0
  - beautifulsoup4==4.12.3
  - bleach==6.1.0
  - bqplot==0.12.43
  - bqplot-gl==0.0.0
  - bqplot-image-gl==1.4.11
  - cachetools==5.3.3
  - casa-formats-io==0.3.0
  - certifi==2024.6.2
  - cffi==1.16.0
  - charset-normalizer==3.3.2
  - chart-studio==1.1.0
  - click==8.1.7
  - cloudpickle==3.0.0
  - comm==0.2.2
  - contourpy==1.2.1
  - cryptography==42.0.8
  - cycler==0.12.1
  - dask==2024.5.2
  - debugpy==1.8.1
  - decorator==5.1.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - echo==0.8.0
  - et-xmlfile==1.1.0
  - executing==2.0.1
  - fast-histogram==0.14
  - fasteners==0.19
  - fastjsonschema==2.19.1
  - filelock==3.14.0
  - fonttools==4.53.0
  - fqdn==1.5.1
  - freetype-py==2.4.0
  - fsspec==2024.6.0
  - glfw==2.7.0
  - glue-core==1.21.0
  - glue-jupyter==0.21.0
  - glue-plotly==0.12.0
  - glue-vispy-viewers==1.2.1
  - h11==0.14.0
  - hsluv==5.0.4
  - httpcore==1.0.5
  - httpx==0.27.0
  - humanize==4.9.0
  - idna==3.7
  - imageio==2.34.1
  - importlib-metadata==7.1.0
  - ipydatawidgets==4.3.5
  - ipykernel==6.29.4
  - ipympl==0.9.4
  - ipython==8.25.0
  - ipython-genutils==0.2.0
  - ipyvolume==0.6.3
  - ipyvue==1.11.1
  - ipyvuetify==1.9.4
  - ipywebrtc==0.6.0
  - ipywidgets==8.1.3
  - isoduration==20.11.0
  - itsdangerous==2.2.0
  - jedi==0.19.1
  - jinja2==3.1.4
  - joblib==1.4.2
  - json5==0.9.25
  - jsonpointer==3.0.0
  - jsonschema==4.22.0
  - jsonschema-specifications==2023.12.1
  - jupyter-client==8.6.2
  - jupyter-core==5.7.2
  - jupyter-events==0.10.0
  - jupyter-lsp==2.2.5
  - jupyter-server==2.14.1
  - jupyter-server-terminals==0.5.3
  - jupyterlab==4.2.2
  - jupyterlab-pygments==0.3.0
  - jupyterlab-server==2.27.2
  - jupyterlab-widgets==3.0.11
  - kiwisolver==1.4.5
  - lazy-loader==0.4
  - locket==1.0.0
  - markdown==3.6
  - markdown-it-py==3.0.0
  - markupsafe==2.1.5
  - matplotlib==3.9.0
  - matplotlib-inline==0.1.7
  - mdurl==0.1.2
  - mistune==3.0.2
  - mpl-scatter-density==0.7
  - nbclient==0.10.0
  - nbconvert==7.16.4
  - nbformat==5.10.4
  - nest-asyncio==1.6.0
  - networkx==3.3
  - notebook==7.2.1
  - notebook-shim==0.2.4
  - numcodecs==0.12.1
  - numpy==1.26.4
  - openpyxl==3.1.3
  - overrides==7.7.0
  - packaging==24.1
  - pandas==2.2.2
  - pandocfilters==1.5.1
  - parso==0.8.4
  - partd==1.4.2
  - pexpect==4.9.0
  - pillow==10.3.0
  - platformdirs==4.2.2
  - plotly==5.22.0
  - prometheus-client==0.20.0
  - prompt-toolkit==3.0.47
  - psutil==5.9.8
  - psygnal==0.11.1
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pvextractor==0.4
  - pycparser==2.22
  - pydantic==2.7.3
  - pydantic-core==2.18.4
  - pyerfa==2.0.1.4
  - pygments==2.18.0
  - pymdown-extensions==10.8.1
  - pyopengl==3.1.7
  - pyparsing==3.1.2
  - python-dateutil==2.9.0.post0
  - python-json-logger==2.0.7
  - pythreejs==2.4.2
  - pytz==2024.1
  - pyyaml==6.0.1
  - pyzmq==26.0.3
  - qtpy==2.4.1
  - radio-beam==0.3.7
  - reacton==1.8.3
  - referencing==0.35.1
  - reproject==0.13.1
  - requests==2.32.3
  - retrying==1.3.4
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rich==13.7.1
  - rich-click==1.8.3
  - rpds-py==0.18.1
  - scikit-image==0.23.2
  - scipy==1.13.1
  - send2trash==1.8.3
  - shapely==2.0.4
  - six==1.16.0
  - sniffio==1.3.1
  - solara==1.33.0
  - solara-enterprise==1.33.0
  - solara-server==1.33.0
  - solara-ui==1.33.0
  - soupsieve==2.5
  - spectral-cube==0.6.5
  - stack-data==0.6.3
  - starlette==0.37.2
  - tenacity==8.3.0
  - terminado==0.18.1
  - tifffile==2024.5.22
  - tinycss2==1.3.0
  - toasty==0.19.0
  - toolz==0.12.1
  - tornado==6.4.1
  - tqdm==4.66.4
  - traitlets==5.14.3
  - traittypes==0.2.1
  - types-python-dateutil==2.9.0.20240316
  - typing-extensions==4.12.2
  - tzdata==2024.1
  - uri-template==1.3.0
  - urllib3==2.2.1
  - uvicorn==0.30.1
  - vispy==0.14.2
  - watchdog==4.0.1
  - watchfiles==0.22.0
  - wcwidth==0.2.13
  - webcolors==24.6.0
  - webencodings==0.5.1
  - websocket-client==1.8.0
  - websockets==12.0
  - widgetsnbextension==4.0.11
  - wwt-data-formats==0.18.1
  - xlrd==2.0.1
  - zarr==2.18.2
  - zipp==3.19.2
  - git+https://github.com/nmearl/ipywwt.git
